# REGRESSION SETUP ALGORITHUMS

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("placement.csv")
df.head()

   cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [ ]:
df.shape

(200, 2)

In [ ]:
x = df.iloc[:,0:1]
y = df.iloc[:,-1]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.svm import SVR

from sklearn.metrics import r2_score

In [ ]:
lr = LinearRegression()
knn = KNeighborsRegressor()
dt = DecisionTreeRegressor()
bagg = BaggingRegressor()
rfr = RandomForestRegressor()
adab = AdaBoostRegressor()
gbr = GradientBoostingRegressor()
svr = SVR()

In [ ]:
lr.fit(x,y)
knn.fit(x,y)
dt.fit(x,y)
bagg.fit(x,y)
rfr.fit(x,y)
adab.fit(x,y)
gbr.fit(x,y)
svr.fit(x,y)

SVR()

In [ ]:
y_pred1 = lr.predict(x_test)
y_pred2 = knn.predict(x_test)
y_pred3 = dt.predict(x_test)
y_pred4 = bagg.predict(x_test)
y_pred5 = rfr.predict(x_test)
y_pred6 = adab.predict(x_test)
y_pred7 = gbr.predict(x_test)
y_pred8 = svr.predict(x_test)

In [ ]:
print("R^2 score for LR",r2_score(y_test,y_pred1))
print("R^2 score for KNN",r2_score(y_test,y_pred2))
print("R^2 score for DT",r2_score(y_test,y_pred3))
print("R^2 score for BAGG",r2_score(y_test,y_pred4))
print("R^2 score for RFR",r2_score(y_test,y_pred5))
print("R^2 score for ADAB",r2_score(y_test,y_pred6))
print("R^2 score for GBR",r2_score(y_test,y_pred7))
print("R^2 score for SVR",r2_score(y_test,y_pred8))

R^2 score for LR 0.7843292550953309
R^2 score for KNN 0.8365244712357395
R^2 score for DT 0.9694768325751455
R^2 score for BAGG 0.9422032012846168
R^2 score for RFR 0.9426472181953599
R^2 score for ADAB 0.804267990065989
R^2 score for GBR 0.9004616418205824
R^2 score for SVR 0.7911187663924211



---



---

# XGBOOST REGRESSOR

In [ ]:
pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.10/dist-packages (1.7.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from xgboost) (1.23.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from xgboost) (1.10.1)

In [ ]:
from xgboost import XGBRegressor
xg = XGBRegressor()
xg.fit(x,y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [ ]:
y_pred9 = xg.predict(x_test)
print("R^2 score for XG",r2_score(y_test,y_pred8))

R^2 score for XG 0.7911187663924211



---



---

# CLASSIFICATION SETUP ALGORITHUMS

In [ ]:
df=pd.read_csv("Social_Network_Ads (for classification).csv")
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
  df.shape

(400, 5)

In [ ]:
x = df.iloc[:,2:4]
y = df.iloc[:,-1]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB, ComplementNB, BernoulliNB

from sklearn.metrics import accuracy_score

In [ ]:
lr = LogisticRegression()
svc = SVC()
knn = KNeighborsClassifier()
dt = DecisionTreeClassifier()
bagg = BaggingClassifier()
rfr = RandomForestClassifier()
adab = AdaBoostClassifier()
gbr = GradientBoostingClassifier()
nb1 = GaussianNB()
nb2 = MultinomialNB()
nb3 = ComplementNB()
nb4 = BernoulliNB()

In [ ]:
lr.fit(x,y)
svc.fit(x,y)
knn.fit(x,y)
dt.fit(x,y)
bagg.fit(x,y)
rfr.fit(x,y)
adab.fit(x,y)
gbr.fit(x,y)
nb1.fit(x,y)
nb2.fit(x,y)
nb3.fit(x,y)
nb4.fit(x,y)

BernoulliNB()

In [ ]:
y_pred1 = lr.predict(x_test)
y_pred2 = svc.predict(x_test)
y_pred3 = knn.predict(x_test)
y_pred4 = dt.predict(x_test)
y_pred5 = bagg.predict(x_test)
y_pred6 = rfr.predict(x_test)
y_pred7 = adab.predict(x_test)
y_pred8 = gbr.predict(x_test)
y_pred9 = nb1.predict(x_test)
y_pred10 = nb2.predict(x_test)
y_pred11 = nb3.predict(x_test)
y_pred12 = nb4.predict(x_test)

In [ ]:
print("accuracy_score for LR",accuracy_score(y_test,y_pred1))
print("accuracy_score for SVC",accuracy_score(y_test,y_pred2))
print("accuracy_score for KNN",accuracy_score(y_test,y_pred3))
print("accuracy_score for DT",accuracy_score(y_test,y_pred4))
print("accuracy_score for BAGG",accuracy_score(y_test,y_pred5))
print("accuracy_score for RFR",accuracy_score(y_test,y_pred6))
print("accuracy_score for ADAB",accuracy_score(y_test,y_pred7))
print("accuracy_score for GBR",accuracy_score(y_test,y_pred8))
print("accuracy_score for NB1",accuracy_score(y_test,y_pred1))
print("accuracy_score for NB2",accuracy_score(y_test,y_pred1))
print("accuracy_score for NB3",accuracy_score(y_test,y_pred1))
print("accuracy_score for NB4",accuracy_score(y_test,y_pred1))

accuracy_score for LR 0.6
accuracy_score for SVC 0.7625
accuracy_score for KNN 0.825
accuracy_score for DT 0.9875
accuracy_score for BAGG 1.0
accuracy_score for RFR 1.0
accuracy_score for ADAB 0.9
accuracy_score for GBR 0.95
accuracy_score for NB1 0.6
accuracy_score for NB2 0.6
accuracy_score for NB3 0.6
accuracy_score for NB4 0.6



---

---

# XGBOOST REGRESSOR

In [ ]:
from xgboost import XGBClassifier
xg = XGBClassifier()
xg.fit(x,y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [ ]:
y_pred13 = xg.predict(x_test)
print("accuracy_score for XG",accuracy_score(y_test,y_pred13))

accuracy_score for XG 0.9875

In [ ]:
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)